#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

test -f "$ROOT/README.md"
test -f "$ROOT/docs/shared/usage.md"
test -f "$ROOT/config/containers/Dockerfile"
test -f "$ROOT/config/patches/apply-hermes-matrix-sync-diagnostics.py"
test -f "$ROOT/config/patches/apply-hermes-matrix-store-home.py"
test -f "$ROOT/lib/shell/common.sh"
test -f "$ROOT/scripts/shared/bootstrap"
test -f "$ROOT/scripts/shared/hermes-build"
test -f "$ROOT/scripts/shared/hermes-upgrade"
test -f "$ROOT/scripts/shared/hermes-start"
test -f "$ROOT/scripts/shared/hermes-open"
test -f "$ROOT/scripts/shared/hermes-status"
test -f "$ROOT/scripts/shared/hermes-logs"
test -f "$ROOT/scripts/shared/hermes-shell"
test -f "$ROOT/scripts/shared/hermes-stop"
test -f "$ROOT/scripts/shared/hermes-remove"
test -f "$ROOT/tests/shared/test-all.sh"
test -f "$ROOT/tests/shared/test-args.sh"
test -f "$ROOT/tests/shared/test-common.sh"
test -f "$ROOT/tests/shared/test-ref-resolution.sh"
test -f "$ROOT/tests/shared/test-runtime.sh"

grep -q '^LABEL hermes.repo_url=\$HERMES_REPO_URL$' "$ROOT/config/containers/Dockerfile"
grep -q '^LABEL hermes.ref=\$HERMES_REF$' "$ROOT/config/containers/Dockerfile"
grep -q '^COPY config/patches /tmp/hermes-patches$' "$ROOT/config/containers/Dockerfile"
grep -q 'libolm-dev' "$ROOT/config/containers/Dockerfile"
grep -q "matrix-nio\[e2e\]" "$ROOT/config/containers/Dockerfile"
grep -q 'python3 /tmp/hermes-patches/apply-hermes-matrix-sync-diagnostics.py' "$ROOT/config/containers/Dockerfile"
grep -q 'python3 /tmp/hermes-patches/apply-hermes-matrix-store-home.py' "$ROOT/config/containers/Dockerfile"
grep -q 'ln -s /data /home/hermes/.hermes' "$ROOT/config/containers/Dockerfile"
grep -q 'import asyncio\\nimport json\\n' "$ROOT/config/patches/apply-hermes-matrix-sync-diagnostics.py"
grep -q 'get_hermes_home' "$ROOT/config/patches/apply-hermes-matrix-store-home.py"
grep -q '_STORE_DIR = get_hermes_home() / "matrix" / "store"' "$ROOT/config/patches/apply-hermes-matrix-store-home.py"
grep -q '^local_build_fingerprint() {$' "$ROOT/lib/shell/common.sh"
grep -q '^current_image_build_fingerprint() {$' "$ROOT/lib/shell/common.sh"
grep -q '^github_repo_slug() {$' "$ROOT/lib/shell/common.sh"
grep -q '^resolve_hermes_ref() {$' "$ROOT/lib/shell/common.sh"
grep -q '^image_exists() {$' "$ROOT/lib/shell/common.sh"
grep -q '^image_label() {$' "$ROOT/lib/shell/common.sh"
grep -q '^show_help() {$' "$ROOT/lib/shell/common.sh"
grep -q '^require_workspace_name() {$' "$ROOT/lib/shell/common.sh"
grep -q '^migrate_legacy_workspace_layout() {$' "$ROOT/lib/shell/common.sh"
grep -q '^"\$SCRIPT_DIR/hermes-build"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^"\$SCRIPT_DIR/hermes-upgrade"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^"\$SCRIPT_DIR/hermes-start" "\$WORKSPACE"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^exec "\$SCRIPT_DIR/hermes-open" "\$WORKSPACE" "\$@"$' "$ROOT/scripts/shared/bootstrap"
grep -q '^if image_exists; then$' "$ROOT/scripts/shared/hermes-build"
grep -q 'hermes.wrapper_fingerprint=' "$ROOT/scripts/shared/hermes-build"
grep -q -- '--restart unless-stopped' "$ROOT/scripts/shared/hermes-start"
grep -q '"\$HERMES_IMAGE_NAME" hermes gateway' "$ROOT/scripts/shared/hermes-start"
grep -q '^CURRENT_REPO_URL="\$(image_label hermes.repo_url)"$' "$ROOT/scripts/shared/hermes-upgrade"
grep -q '^CURRENT_REF="\$(image_label hermes.ref)"$' "$ROOT/scripts/shared/hermes-upgrade"
grep -q '^CURRENT_BUILD_FINGERPRINT="\$(current_image_build_fingerprint)"$' "$ROOT/scripts/shared/hermes-upgrade"
grep -q '"\$HERMES_HOME_DIR:/data"' "$ROOT/scripts/shared/hermes-start"
grep -q '"\$HERMES_WORKSPACE_DIR:/workspace"' "$ROOT/scripts/shared/hermes-start"
if grep -q -- '--env-file' "$ROOT/scripts/shared/hermes-start"; then
  printf 'assertion failed: hermes-start should not use --env-file\n' >&2
  exit 1
fi

echo "Layout checks passed"
