from pathlib import Path
import re


path = Path("/home/hermes/hermes-agent/gateway/platforms/matrix.py")
text = path.read_text(encoding="utf-8")


def replace_once(old: str, new: str, description: str) -> None:
    global text
    if old not in text:
        raise SystemExit(f"could not apply matrix encrypted-media patch: {description}")
    text = text.replace(old, new, 1)


def replace_regex_once(pattern: str, new: str, description: str) -> None:
    global text
    updated, count = re.subn(pattern, new, text, count=1, flags=re.S)
    if count != 1:
        raise SystemExit(f"could not apply matrix encrypted-media patch: {description}")
    text = updated


replace_once(
    '        # Register event callbacks.\n'
    '        client.add_event_callback(self._on_room_message, nio.RoomMessageText)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageImage)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageAudio)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageVideo)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageFile)\n'
    '        client.add_event_callback(self._on_invite, nio.InviteMemberEvent)\n\n'
    '        # If E2EE: handle encrypted events.\n'
    '        if self._encryption and hasattr(client, "olm"):\n'
    '            client.add_event_callback(\n'
    '                self._on_room_message, nio.MegolmEvent\n'
    '            )\n'
    '            client.add_to_device_callback(\n'
    '                self._on_key_verification,\n'
    '                (nio.KeyVerificationStart, nio.KeyVerificationCancel,\n'
    '                 nio.KeyVerificationKey, nio.KeyVerificationMac)\n'
    '            )\n',
    '        # Register event callbacks.\n'
    '        client.add_event_callback(self._on_room_message, nio.RoomMessageText)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageImage)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageAudio)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageVideo)\n'
    '        client.add_event_callback(self._on_room_message_media, nio.RoomMessageFile)\n'
    '        client.add_event_callback(self._on_invite, nio.InviteMemberEvent)\n\n'
    '        # If E2EE: handle encrypted events and encrypted media callbacks.\n'
    '        if self._encryption and getattr(client, "olm", None):\n'
    '            client.add_event_callback(\n'
    '                self._on_room_message, nio.MegolmEvent\n'
    '            )\n'
    '            client.add_to_device_callback(\n'
    '                self._on_key_verification,\n'
    '                (nio.KeyVerificationStart, nio.KeyVerificationCancel,\n'
    '                 nio.KeyVerificationKey, nio.KeyVerificationMac)\n'
    '            )\n'
    '            for event_name in (\n'
    '                "RoomEncryptedImage",\n'
    '                "RoomEncryptedAudio",\n'
    '                "RoomEncryptedVideo",\n'
    '                "RoomEncryptedFile",\n'
    '            ):\n'
    '                event_cls = getattr(nio, event_name, None)\n'
    '                if event_cls is not None:\n'
    '                    client.add_event_callback(self._on_room_message_media, event_cls)\n',
    "callback registration includes encrypted media classes",
)

replace_once(
    '    def _is_duplicate_event(self, event_id) -> bool:\n'
    '        """Return True if this event was already processed. Tracks the ID otherwise."""\n'
    '        if not event_id:\n'
    '            return False\n'
    '        if event_id in self._processed_events_set:\n'
    '            return True\n'
    '        if len(self._processed_events) == self._processed_events.maxlen:\n'
    '            evicted = self._processed_events[0]\n'
    '            self._processed_events_set.discard(evicted)\n'
    '        self._processed_events.append(event_id)\n'
    '        self._processed_events_set.add(event_id)\n'
    '        return False\n',
    '    def _is_duplicate_event(self, event_id) -> bool:\n'
    '        """Return True if this event was already processed. Tracks the ID otherwise."""\n'
    '        if not event_id:\n'
    '            return False\n'
    '        if event_id in self._processed_events_set:\n'
    '            return True\n'
    '        if len(self._processed_events) == self._processed_events.maxlen:\n'
    '            evicted = self._processed_events[0]\n'
    '            self._processed_events_set.discard(evicted)\n'
    '        self._processed_events.append(event_id)\n'
    '        self._processed_events_set.add(event_id)\n'
    '        return False\n\n'
    '    def _allow_reprocess_event(self, event_id) -> None:\n'
    '        """Remove an event from the dedupe cache so a retried decrypted form can run."""\n'
    '        if not event_id:\n'
    '            return\n'
    '        if event_id in self._processed_events_set:\n'
    '            self._processed_events_set.discard(event_id)\n'
    '            try:\n'
    '                self._processed_events.remove(event_id)\n'
    '            except ValueError:\n'
    '                pass\n',
    "allow buffered Megolm events to be reprocessed after decryption",
)

replace_once(
    '            # Route to the appropriate handler based on decrypted type.\n'
    '            try:\n'
    '                if isinstance(decrypted, nio.RoomMessageText):\n'
    '                    await self._on_room_message(room, decrypted)\n'
    '                elif isinstance(\n'
    '                    decrypted,\n'
    '                    (nio.RoomMessageImage, nio.RoomMessageAudio,\n'
    '                     nio.RoomMessageVideo, nio.RoomMessageFile),\n'
    '                ):\n'
    '                    await self._on_room_message_media(room, decrypted)\n'
    '                else:\n'
    '                    logger.debug(\n'
    '                        "Matrix: decrypted event %s has unhandled type %s",\n'
    '                        getattr(event, "event_id", "?"),\n'
    '                        type(decrypted).__name__,\n'
    '                    )\n',
    '            # Route to the appropriate handler based on decrypted type.\n'
    '            try:\n'
    '                self._allow_reprocess_event(getattr(decrypted, "event_id", None))\n'
    '                decrypted_media_types = tuple(\n'
    '                    cls\n'
    '                    for cls in (\n'
    '                        nio.RoomMessageImage,\n'
    '                        nio.RoomMessageAudio,\n'
    '                        nio.RoomMessageVideo,\n'
    '                        nio.RoomMessageFile,\n'
    '                        getattr(nio, "RoomEncryptedImage", None),\n'
    '                        getattr(nio, "RoomEncryptedAudio", None),\n'
    '                        getattr(nio, "RoomEncryptedVideo", None),\n'
    '                        getattr(nio, "RoomEncryptedFile", None),\n'
    '                    )\n'
    '                    if cls is not None\n'
    '                )\n'
    '                if isinstance(decrypted, nio.RoomMessageText):\n'
    '                    await self._on_room_message(room, decrypted)\n'
    '                elif decrypted_media_types and isinstance(decrypted, decrypted_media_types):\n'
    '                    await self._on_room_message_media(room, decrypted)\n'
    '                else:\n'
    '                    logger.debug(\n'
    '                        "Matrix: decrypted event %s has unhandled type %s",\n'
    '                        getattr(event, "event_id", "?"),\n'
    '                        type(decrypted).__name__,\n'
    '                    )\n',
    "retry path reprocesses decrypted media without duplicate drops",
)

replace_regex_once(
    r'    async def _on_room_message_media\(self, room: Any, event: Any\) -> None:\n.*?        await self.handle_message\(msg_event\)\n',
    '    def _extract_download_body(self, response: Any) -> Optional[bytes]:\n'
    '        """Extract raw bytes from matrix-nio download responses."""\n'
    '        body = getattr(response, "body", None)\n'
    '        if isinstance(body, bytearray):\n'
    '            return bytes(body)\n'
    '        if isinstance(body, bytes):\n'
    '            return body\n'
    '        return None\n\n'
    '    def _get_media_extension(self, media_type: str, default: str) -> str:\n'
    '        """Resolve a safe file extension from MIME type with sensible fallbacks."""\n'
    '        normalized_exts = {\n'
    '            "audio/ogg": ".ogg",\n'
    '            "application/ogg": ".ogg",\n'
    '            "audio/opus": ".ogg",\n'
    '        }\n'
    '        if media_type in normalized_exts:\n'
    '            return normalized_exts[media_type]\n'
    '        ext = mimetypes.guess_extension(media_type or "") or default\n'
    '        if ext == ".jpe":\n'
    '            return ".jpg"\n'
    '        if ext == ".oga":\n'
    '            return ".ogg"\n'
    '        return ext\n\n'
    '    def _get_encrypted_media_content(self, event: Any) -> Dict[str, Any]:\n'
    '        """Return the Matrix event content dict for encrypted media events."""\n'
    '        source = getattr(event, "source", {})\n'
    '        if not isinstance(source, dict):\n'
    '            return {}\n'
    '        content = source.get("content", {})\n'
    '        return content if isinstance(content, dict) else {}\n\n'
    '    def _get_encrypted_file_info(self, event: Any) -> Optional[Dict[str, Any]]:\n'
    '        """Return the encrypted file metadata block from the event content."""\n'
    '        file_info = self._get_encrypted_media_content(event).get("file")\n'
    '        return file_info if isinstance(file_info, dict) else None\n\n'
    '    def _get_encrypted_media_url(self, event: Any) -> str:\n'
    '        """Resolve the MXC URL for encrypted media, preferring content.file.url."""\n'
    '        file_info = self._get_encrypted_file_info(event) or {}\n'
    '        url = file_info.get("url", "")\n'
    '        if isinstance(url, str) and url:\n'
    '            return url\n'
    '        fallback = getattr(event, "url", "")\n'
    '        return fallback if isinstance(fallback, str) else ""\n\n'
    '    def _get_encrypted_filename(self, content: Dict[str, Any], media_type: str) -> str:\n'
    '        """Choose a safe filename for encrypted file/video cache writes."""\n'
    '        filename = str(content.get("filename") or content.get("body") or "").strip()\n'
    '        if filename and filename not in (".", ".."):\n'
    '            return Path(filename).name\n'
    '        default_name = "video" if media_type.startswith("video/") else "document"\n'
    '        ext = self._get_media_extension(media_type, ".bin")\n'
    '        return f"{default_name}{ext}"\n\n'
    '    def _decrypt_matrix_attachment(\n'
    '        self,\n'
    '        ciphertext: bytes,\n'
    '        key: Any,\n'
    '        sha256: str,\n'
    '        iv: str,\n'
    '    ) -> bytes:\n'
    '        """Decrypt Matrix encrypted attachment bytes using nio\'s helper."""\n'
    '        from nio.crypto import decrypt_attachment\n\n'
    '        if isinstance(key, dict):\n'
    '            key = key.get("k", "")\n'
    '        if not isinstance(key, str) or not key:\n'
    '            raise ValueError("Matrix encrypted attachment missing key.k")\n'
    '        if not isinstance(sha256, str) or not sha256:\n'
    '            raise ValueError("Matrix encrypted attachment missing hashes.sha256")\n'
    '        if not isinstance(iv, str) or not iv:\n'
    '            raise ValueError("Matrix encrypted attachment missing iv")\n'
    '        return decrypt_attachment(ciphertext, key, sha256, iv)\n\n'
    '    async def _on_room_message_media(self, room: Any, event: Any) -> None:\n'
    '        """Handle incoming media messages (images, audio, video, files)."""\n'
    '        import nio\n\n'
    '        encrypted_image_cls = getattr(nio, "RoomEncryptedImage", None)\n'
    '        encrypted_audio_cls = getattr(nio, "RoomEncryptedAudio", None)\n'
    '        encrypted_video_cls = getattr(nio, "RoomEncryptedVideo", None)\n'
    '        encrypted_file_cls = getattr(nio, "RoomEncryptedFile", None)\n'
    '        encrypted_media_types = tuple(\n'
    '            cls\n'
    '            for cls in (\n'
    '                encrypted_image_cls,\n'
    '                encrypted_audio_cls,\n'
    '                encrypted_video_cls,\n'
    '                encrypted_file_cls,\n'
    '            )\n'
    '            if cls is not None\n'
    '        )\n'
    '        image_event_types = tuple(cls for cls in (nio.RoomMessageImage, encrypted_image_cls) if cls is not None)\n'
    '        audio_event_types = tuple(cls for cls in (nio.RoomMessageAudio, encrypted_audio_cls) if cls is not None)\n'
    '        video_event_types = tuple(cls for cls in (nio.RoomMessageVideo, encrypted_video_cls) if cls is not None)\n'
    '        file_event_types = tuple(cls for cls in (nio.RoomMessageFile, encrypted_file_cls) if cls is not None)\n\n'
    '        # Ignore own messages.\n'
    '        if event.sender == self._user_id:\n'
    '            return\n\n'
    '        # Deduplicate by event ID.\n'
    '        if self._is_duplicate_event(getattr(event, "event_id", None)):\n'
    '            return\n\n'
    '        # Startup grace.\n'
    '        event_ts = getattr(event, "server_timestamp", 0) / 1000.0\n'
    '        if event_ts and event_ts < self._startup_ts - _STARTUP_GRACE_SECONDS:\n'
    '            return\n\n'
    '        source_content = self._get_encrypted_media_content(event)\n'
    '        body = getattr(event, "body", "") or source_content.get("body", "") or ""\n'
    '        url = getattr(event, "url", "")\n'
    '        is_encrypted_media = bool(encrypted_media_types and isinstance(event, encrypted_media_types))\n\n'
    '        # Convert plaintext mxc:// URLs to HTTP URLs for downstream processing.\n'
    '        http_url = ""\n'
    '        if not is_encrypted_media and url and url.startswith("mxc://"):\n'
    '            http_url = self._mxc_to_http(url)\n\n'
    '        # Determine message type from event class.\n'
    '        # Use the MIME type from the event\'s content info when available,\n'
    '        # falling back to category-level MIME types for downstream matching\n'
    '        # (gateway/run.py checks startswith("image/"), startswith("audio/"), etc.)\n'
    '        content_info = source_content if is_encrypted_media else (getattr(event, "content", {}) if isinstance(getattr(event, "content", None), dict) else source_content)\n'
    '        event_mimetype = (content_info.get("info") or {}).get("mimetype", "")\n'
    '        media_type = "application/octet-stream"\n'
    '        msg_type = MessageType.DOCUMENT\n'
    '        is_voice_message = False\n\n'
    '        if image_event_types and isinstance(event, image_event_types):\n'
    '            msg_type = MessageType.PHOTO\n'
    '            media_type = event_mimetype or "image/png"\n'
    '        elif audio_event_types and isinstance(event, audio_event_types):\n'
    '            if source_content.get("org.matrix.msc3245.voice") is not None:\n'
    '                is_voice_message = True\n'
    '                msg_type = MessageType.VOICE\n'
    '            else:\n'
    '                msg_type = MessageType.AUDIO\n'
    '            media_type = event_mimetype or "audio/ogg"\n'
    '        elif video_event_types and isinstance(event, video_event_types):\n'
    '            msg_type = MessageType.VIDEO\n'
    '            media_type = event_mimetype or "video/mp4"\n'
    '        elif event_mimetype:\n'
    '            media_type = event_mimetype\n\n'
    '        cached_path = None\n'
    '        media_urls = [http_url] if http_url else None\n\n'
    '        if is_encrypted_media:\n'
    '            try:\n'
    '                from gateway.platforms.base import (\n'
    '                    cache_audio_from_bytes,\n'
    '                    cache_document_from_bytes,\n'
    '                    cache_image_from_bytes,\n'
    '                )\n\n'
    '                file_info = self._get_encrypted_file_info(event)\n'
    '                media_url = self._get_encrypted_media_url(event)\n'
    '                if not file_info:\n'
    '                    raise ValueError("Matrix encrypted media missing content.file metadata")\n'
    '                if not media_url:\n'
    '                    raise ValueError("Matrix encrypted media missing MXC URL")\n\n'
    '                try:\n'
    '                    download_resp = await self._client.download(mxc=media_url)\n'
    '                except TypeError:\n'
    '                    download_resp = await self._client.download(media_url)\n'
    '                ciphertext = self._extract_download_body(download_resp)\n'
    '                if ciphertext is None:\n'
    '                    raise ValueError(f"Matrix encrypted media download produced no body: {download_resp!r}")\n\n'
    '                plaintext = self._decrypt_matrix_attachment(\n'
    '                    ciphertext,\n'
    '                    file_info.get("key", ""),\n'
    '                    (file_info.get("hashes") or {}).get("sha256", ""),\n'
    '                    file_info.get("iv", ""),\n'
    '                )\n\n'
    '                if msg_type == MessageType.PHOTO:\n'
    '                    cached_path = cache_image_from_bytes(\n'
    '                        plaintext,\n'
    '                        ext=self._get_media_extension(media_type, ".jpg"),\n'
    '                    )\n'
    '                elif msg_type in (MessageType.VOICE, MessageType.AUDIO):\n'
    '                    cached_path = cache_audio_from_bytes(\n'
    '                        plaintext,\n'
    '                        self._get_media_extension(media_type, ".ogg"),\n'
    '                    )\n'
    '                else:\n'
    '                    cached_path = cache_document_from_bytes(\n'
    '                        plaintext,\n'
    '                        self._get_encrypted_filename(source_content, media_type),\n'
    '                    )\n'
    '                logger.info("Matrix: cached encrypted media %s to %s", event.event_id, cached_path)\n'
    '            except Exception as exc:\n'
    '                logger.warning(\n'
    '                    "Matrix: failed to decrypt/cache encrypted media %s: %s",\n'
    '                    getattr(event, "event_id", "?"),\n'
    '                    exc,\n'
    '                )\n'
    '                media_urls = None\n'
    '        else:\n'
    '            # For images, download and cache locally so vision tools can access them.\n'
    '            # Matrix MXC URLs require authentication, so direct URL access fails.\n'
    '            if msg_type == MessageType.PHOTO and url:\n'
    '                try:\n'
    '                    from gateway.platforms.base import cache_image_from_bytes\n\n'
    '                    ext_map = {\n'
    '                        "image/jpeg": ".jpg", "image/png": ".png",\n'
    '                        "image/gif": ".gif", "image/webp": ".webp",\n'
    '                    }\n'
    '                    ext = ext_map.get(event_mimetype, ".jpg")\n'
    '                    download_resp = await self._client.download(url)\n'
    '                    body_bytes = self._extract_download_body(download_resp)\n'
    '                    if body_bytes is not None:\n'
    '                        cached_path = cache_image_from_bytes(body_bytes, ext=ext)\n'
    '                        logger.info("[Matrix] Cached user image at %s", cached_path)\n'
    '                except Exception as e:\n'
    '                    logger.warning("[Matrix] Failed to cache image: %s", e)\n\n'
    '            # For voice messages, cache audio locally for transcription tools.\n'
    '            # Use the authenticated nio client to download (Matrix requires auth for media).\n'
    '            if is_voice_message and url and url.startswith("mxc://"):\n'
    '                try:\n'
    '                    from gateway.platforms.base import cache_audio_from_bytes\n\n'
    '                    resp = await self._client.download(mxc=url)\n'
    '                    body_bytes = self._extract_download_body(resp)\n'
    '                    if body_bytes is not None:\n'
    '                        ext = self._get_media_extension(media_type, ".ogg")\n'
    '                        local_path = cache_audio_from_bytes(body_bytes, ext)\n'
    '                        media_urls = [local_path]\n'
    '                        logger.debug("Matrix: cached voice message to %s", local_path)\n'
    '                    else:\n'
    '                        logger.warning("Matrix: failed to download voice: %s", getattr(resp, "message", resp))\n'
    '                except Exception as e:\n'
    '                    logger.warning("Matrix: failed to cache voice message, using HTTP URL: %s", e)\n\n'
    '        is_dm = self._dm_rooms.get(room.room_id, False)\n'
    '        if not is_dm and room.member_count == 2:\n'
    '            is_dm = True\n'
    '        chat_type = "dm" if is_dm else "group"\n\n'
    '        # Thread/reply detection.\n'
    '        relates_to = source_content.get("m.relates_to", {})\n'
    '        thread_id = None\n'
    '        if relates_to.get("rel_type") == "m.thread":\n'
    '            thread_id = relates_to.get("event_id")\n\n'
    '        source = self.build_source(\n'
    '            chat_id=room.room_id,\n'
    '            chat_type=chat_type,\n'
    '            user_id=event.sender,\n'
    '            user_name=self._get_display_name(room, event.sender),\n'
    '            thread_id=thread_id,\n'
    '        )\n\n'
    '        # Use cached local path when media bytes were downloaded successfully.\n'
    '        if cached_path:\n'
    '            media_urls = [cached_path]\n'
    '        elif is_encrypted_media:\n'
    '            media_urls = None\n'
    '        media_types = [media_type] if media_urls else None\n\n'
    '        msg_event = MessageEvent(\n'
    '            text=body,\n'
    '            message_type=msg_type,\n'
    '            source=source,\n'
    '            raw_message=getattr(event, "source", {}),\n'
    '            message_id=event.event_id,\n'
    '            media_urls=media_urls,\n'
    '            media_types=media_types,\n'
    '        )\n\n'
    '        await self.handle_message(msg_event)\n',
    "media handler supports encrypted media callbacks, decrypts attachments, and caches local files",
)

if 'client.add_to_device_callback(' not in text:
    raise SystemExit(
        "could not apply matrix encrypted-media patch: verification callback missing after rewrite"
    )


path.write_text(text, encoding="utf-8")
